# Generated by Django 5.1 on 2024-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50)),
                ('salary_range', models.CharField(max_length=255)),
                ('application_deadline', models.DateField()),
                ('required_qualifications', models.TextField()),
                ('preferred_qualifications', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
