# Generated by Django 5.1 on 2024-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('Department', 'Department'), ('Location', 'Location'), ('Employment Type', 'Employment Type')], max_length=50)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
