# Generated by Django 5.1 on 2024-09-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='category_type',
            field=models.CharField(choices=[('Department', 'Department'), ('Location', 'Location'), ('EmploymentType', 'Employment Type')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Department'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings_department', to='users.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.ForeignKey(limit_choices_to={'category_type': 'EmploymentType'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings_employment_type', to='users.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Location'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings_location', to='users.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
