from django.urls import path
from . import views
from .views import dashboard, applications_management
from django.urls import path
from .views import dashboard, applications_management, view_application,move_to_next_stage , reject_application , application_details, notifications_screen,interview_scheduling_dashboard, view_interview,reschedule_interview, schedule_interview,application_details, update_status, compose_message,create_report,report_details,edit_report,delete_report,export_report

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_recovery/', views.password_recovery, name='password_recovery'),
    path('password_reset_confirm/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('', views.home, name='home'),
    path('create-job/', views.create_job, name='create_job'),
    path('job-drafts/', views.job_drafts, name='job_drafts'),
    path('edit-job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('delete-job/<int:job_id>/', views.delete_job, name='delete_job'),
    path('published-jobs/', views.published_jobs, name='published_jobs'),
    path('view-job/<int:job_id>/', views.view_job, name='view_job'),
    path('unpublish-job/<int:job_id>/', views.unpublish_job, name='unpublish_job'),
    path('job-categories/', views.job_categories, name='job_categories'),
    path('add-category/', views.add_category, name='add_category'),
    path('edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete-category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('application_forms/', views.application_forms_management, name='application_forms_management'),
    path('application_forms/create/', views.create_application_form, name='create_application_form'),
    path('application_forms/edit/<int:form_id>/', views.edit_application_form, name='edit_application_form'),
    path('application_forms/delete/<int:form_id>/', views.delete_application_form, name='delete_application_form'),
    path('', dashboard, name='dashboard'),
    path('applications/', applications_management, name='applications_management'),
    path('view_application/<int:application_id>/', view_application, name='view_application'),
    path('move_to_next_stage/<int:application_id>/', move_to_next_stage, name='move_to_next_stage'),
    path('reject_application/<int:application_id>/', reject_application, name='reject_application'),
    path('applications_management/', applications_management, name='applications_management'),
    path('applications/', views.applications_management, name='applications_management'),
    path('', dashboard, name='dashboard'),
    path('applications/', applications_management, name='applications_management'),
    path('view_application/<int:application_id>/', view_application, name='view_application'),
    path('', dashboard, name='dashboard'),
    path('applications/', applications_management, name='applications_management'),
    path('view_application/<int:application_id>/', view_application, name='view_application'),
    path('move_to_next_stage/<int:application_id>/', move_to_next_stage, name='move_to_next_stage'),
    path('', dashboard, name='dashboard'),
    path('applications/', applications_management, name='applications_management'),
    path('view_application/<int:application_id>/', view_application, name='view_application'),
    path('move_to_next_stage/<int:application_id>/', move_to_next_stage, name='move_to_next_stage'),
    path('reject_application/<int:application_id>/', reject_application, name='reject_application'),
    path('application_details/<int:application_id>/', application_details, name='application_details'),
    path('notifications/', notifications_screen, name='notifications_screen'),
    path('interview_scheduling_dashboard/', interview_scheduling_dashboard, name='interview_scheduling_dashboard'),
    path('view_interview/<int:interview_id>/', view_interview, name='view_interview'),
    path('reschedule_interview/<int:interview_id>/', reschedule_interview, name='reschedule_interview'),
    path('schedule_interview/', schedule_interview, name='schedule_interview'),
    path('view_interview/<int:interview_id>/', view_interview, name='view_interview'),
    path('interview/<int:interview_id>/', views.interview_details, name='interview_details'),
    path('interview/<int:interview_id>/reschedule/', views.reschedule_interview, name='reschedule_interview'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('application/<int:application_id>/', application_details, name='application_details'),
    path('update-status/<int:application_id>/', update_status, name='update_status'),
    path('compose-message/', views.compose_message, name='compose_message'),
    path('applications/<int:application_id>/update-status/', views.update_status, name='update_status'),
    path('applications/<int:application_id>/compose-message/', views.compose_message, name='compose_message'),
    path('update-status/<int:application_id>/', views.update_status, name='update_status'),
    path('custom-reports/', views.custom_reports_dashboard, name='custom_reports_dashboard'),
    path('create-report/', views.create_report, name='create_report'),
    path('view-report/<int:report_id>/', views.view_report, name='view_report'),
    path('edit-report/<int:report_id>/', views.edit_report, name='edit_report'),
    path('delete-report/<int:report_id>/', views.delete_report, name='delete_report'),
    path('export-report/<int:report_id>/', views.export_report, name='export_report'),
    path('create_report/', create_report, name='create_report'),
    path('report/<int:report_id>/', report_details, name='report_details'),
    path('edit_report/<int:report_id>/', edit_report, name='edit_report'),
    path('delete_report/<int:report_id>/', delete_report, name='delete_report'),
    path('export_report/<int:report_id>/', export_report, name='export_report'),
]


